### ISSUE TITLE
Which is the key to trigger the magic?

### ISSUE THREAD

**Issue by difanzhong** [VincentKos/php-docblock-generator#1]
very nice extension. Just wonder how to trigger the effect

**Comment by ruger-io** [comment]
open your Keyboard Shortcuts
create a key binding in your keybindings.json file

add the following if you like this command

```
{
            "key": "cmd+alt+/",
            "command": "php-docblock-generator.createDocBlock",
            "when": "editorTextFocus"
}
```

Restart VSCode

**Comment by difanzhong** [comment]
Thanks so much dude. Just set that combination.
