### ISSUE TITLE
Auto-generate comment upon entering /**

### ISSUE THREAD

**Issue by BernhardWebstudio** [VincentKos/php-docblock-generator#3]
Feature request: upon entering `/**` + Enter on the line above the relevant declaration, it would be nice to have the comments automatically generated.

**Comment by BernhardWebstudio** [comment]
I am sorry. Maybe the following Gif (from NetBeans) can help: 
![Autocomplete PHP Docs](https://user-images.githubusercontent.com/8596965/41989928-47346ef2-7a41-11e8-99d4-7b4fe2e7003a.gif)

**Comment by VincentKos** [comment]
Oh ok I get it. Sound like a good idea, but don't know if it will not break the usage of other extension like "DocBlocks". 

I'll think about it for the next release.

**Comment by BernhardWebstudio** [comment]
I am sorry, I did not know that one. Yeah, probably this feature would be redundant as these two extensions together provide the desired functionality. Thanks!
